site_name: TRE Operators Guide
site_description: Documentation for Trusted Research Environment (TRE) operators in the context of Federated EOSC-ENTRUST
site_author: EOSC-ENTRUST Team
repo_url: https://github.com/unioslo/tre-operators-docs
use_directory_urls: true
theme:
  name: readthedocs

nav:
  - Home: index.md
  - EOSC-ENTRUST Overview: eosc-overview.md
  - TRE Fundamentals: fundamentals.md
  - Deployment Guide:
      - Architecture: deployment/index.md
  - Federation Integration: federation.md
  - Operations & Maintenance: operations.md
  - Compliance & Certification: compliance.md
  - Best Practices: best-practices.md
  - Appendices:
      - Glossary: appendices/glossary.md
      - Reference Architecture: appendices/reference-architecture.md
      - Resources: appendices/resources.md
