site_name: TRE Operators Guide
site_description: Documentation for Trusted Research Environment (TRE) operators in the context of Federated EOSC-ENTRUST
site_author: EOSC-ENTRUST Team
repo_url: https://github.com/unioslo/tre-operators-docs
use_directory_urls: true
theme:
  name: material

features:
    - search.suggest
    - search.highlight
    - navigation.tabs

markdown_extensions:
  - pymdownx.superfences  # Required to render the MyST-like warning/note boxes nicely

extra_css:
  - stylesheets/home.css

nav:
  - Home: index.md
  - "M1: TRE Fundamentals": fundamentals.md
  - "M2: Architecture": modules/architecture/index.md
  - "M3: Interface Definitions": modules/interfaces/index.md
  - "M4: Operating Procedures": modules/procedures/index.md
  - "M5: Template Legal Agreements": modules/legal/index.md
  - "M6: Federation": federation.md
  - Appendices:
      - Glossary: appendices/glossary.md
      - Reference Architecture: appendices/reference-architecture.md
      - Resources: appendices/resources.md
      - Copilot Acknowledgement: appendices/copilot-acknowledgement.md